language: python
python:
  - 2.7
  - 3.4
  - 3.5

os:
  - linux
sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=3.4
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=3.5
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=2.7

before_install:
  - sudo chmod +x .travis/install.sh && sudo chown $USER .travis/install.sh && /bin/bash .travis/install.sh

install:
  - source bg-env/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python -m pytest tests